# Generated by Django 3.0 on 2020-02-20 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id_device', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Dispositivo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('processor', models.TextField(verbose_name='Procesador')),
                ('internal_storage', models.CharField(max_length=10, verbose_name='Almacenamiento Interno')),
                ('ram', models.CharField(max_length=10, verbose_name='RAM')),
                ('os', models.CharField(max_length=30, verbose_name='Sistema Operativo')),
                ('eth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ethernet')),
                ('wifi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wi-Fi')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['id_device'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Evaluación')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('status', models.IntegerField(verbose_name='Estado')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['id_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_infected', models.BooleanField()),
                ('is_vulnerated', models.BooleanField()),
                ('id_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='evaluations.Device')),
            ],
            options={
                'verbose_name': 'Estado del dipositivo',
                'verbose_name_plural': 'Estado del dispositivo',
                'ordering': ['is_vulnerated', 'id_device'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='id_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.Evaluation'),
        ),
    ]
