# Generated by Django 3.0 on 2020-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estado'),
        ),
    ]
