# Generated by Django 3.0 on 2020-02-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20200220_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.IntegerField(max_length=1, verbose_name='Estado'),
        ),
    ]
