# Generated by Django 3.0 on 2020-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_auto_20200220_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.IntegerField(verbose_name='Estado'),
        ),
    ]
