# Generated by Django 3.0 on 2020-02-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_evaluation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.IntegerField(choices=[('A', 'Activa'), ('P', 'En Pausa'), ('F', 'Finalizada')], verbose_name='Estado'),
        ),
    ]
