# Generated by Django 3.0 on 2020-02-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_auto_20200227_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('A', 'Activa'), ('P', 'En Pausa'), ('F', 'Finalizada')], max_length=1, verbose_name='Estado'),
        ),
    ]
