# Generated by Django 3.0 on 2020-02-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('given_name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('first_surname', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('second_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno')),
                ('phone_number', models.IntegerField(max_length=10, verbose_name='Número Telefónico')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Se Unió')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último inicio de Sesión')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
