# Generated by Django 3.0 on 2020-02-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200213_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(verbose_name='Número Telefónico'),
        ),
    ]
