# Generated by Django 3.0 on 2020-02-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200227_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(verbose_name='Número Telefónico'),
        ),
    ]
